{% set version = "2.1.3" %}

package:
  name: bob.learn.mlp
  version: {{ version }}

source:
  fn: bob.learn.mlp-{{ version }}.zip
  md5: 1e81cf83e9eb90370b59ec0670a6b6e4
  url: https://pypi.io/packages/source/b/bob.learn.mlp/bob.learn.mlp-{{ version }}.zip

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python
    - setuptools
    - bob.extension >2.0.4
    - bob.blitz
    - bob.core
    - bob.io.base
    - bob.math
    - bob.learn.activation
    - cmake
    - pkg-config
    - boost 1.61.*

  run:
    - python
    - bob.extension >2.0.4
    - bob.blitz
    - bob.core
    - bob.io.base
    - bob.math
    - bob.learn.activation
    - boost 1.61.*

test:
  commands:
    - nosetests -sv bob.learn.mlp

  imports:
    - bob
    - bob.learn
    - bob.learn.mlp

  requires:
    - nose

about:
  home: https://www.idiap.ch/software/bob/
  license: Modified BSD License (3-clause)
  summary: Bob's Multi-layer Perceptron and Trainers

extra:
  recipe-maintainers:
    - 183amir
